- name: Installer et configurer l'agent Zabbix sur les serveurs Linux  # Nom du playbook
  hosts: all  # Cible tous les hôtes
  become: true  # Exécution avec privilèges root

  vars:
    zabbix_hostnames:  # Dictionnaire IP -> hostname
      "172.16.5.8": "Terraform"
      "172.16.3.7": "Splunk"
      "172.16.3.6": "Rsyslog"
      "172.16.5.9": "Rsync"
      "172.16.2.5": "NTP"

  tasks:
    - name: Installer le paquet zabbix-agent sans ajout de repo
      apt:
        name: zabbix-agent  # Paquet à installer
        state: present
        update_cache: yes  # Met à jour la liste des paquets avant installation

    - name: Configurer le fichier zabbix_agentd.conf (Server)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf  # Fichier de configuration agent
        regexp: '^Server='  # Recherche la ligne Server=
        line: 'Server=172.16.5.6'  # Définit l'IP du serveur Zabbix

    - name: Configurer le fichier zabbix_agentd.conf (ServerActive)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='  # Recherche la ligne ServerActive=
        line: 'ServerActive=172.16.5.6'  # Définit l'IP du serveur actif Zabbix

    - name: Définir le hostname Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='  # Recherche la ligne Hostname=
        line: "Hostname={{ zabbix_hostnames[inventory_hostname] | default(ansible_default_ipv4.address) }}"  
        # Définit le hostname selon la variable ou l'IP par défaut

    - name: Redémarrer proprement le service zabbix-agent
      command: systemctl restart zabbix-agent.service  # Redémarre l'agent pour appliquer la config
